
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/artgallery
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
success:
  message: Success
failure:
  message: Failed
secret:
  key: AuthenticationServiceForVirtualArtGalleryApplication
error:
  code: ERR001
role:
  list: ROLE_USER,ROLE_ADMIN,ROLE_CURATOR,ROLE_ARTIST,ROLE_SPONSOR